name: Предложить улучшение
description: Новая функция или изменение существующего поведения
title: "[Идея] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: project
    attributes:
      label: Проект
      options:
        - DevGram Android
        - DevGram SDK
        - DevGram Builder
        - Документация
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему решает предложение
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
    validations:
      required: true
